import 'package:xterm/xterm.dart' as xt;
import 'package:flutter/material.dart';

xt.TerminalTheme getTerminalTheme(String themeName) {
  switch (themeName) {
    case 'dracula':
      return const xt.TerminalTheme(
        background: Color(0xFF282A36),
        foreground: Color(0xFFF8F8F2),
        cursor: Color(0xFFF8F8F2),
        selection: Color(0xFF44475A),
        black: Color(0xFF21222C),
        red: Color(0xFFFF5555),
        green: Color(0xFF50FA7B),
        yellow: Color(0xFFF1FA8C),
        blue: Color(0xFFBD93F9),
        magenta: Color(0xFFFF79C6),
        cyan: Color(0xFF8BE9FD),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF6272A4),
        brightRed: Color(0xFFFF6E6E),
        brightGreen: Color(0xFF69FF94),
        brightYellow: Color(0xFFFFFFA5),
        brightBlue: Color(0xFFD6ACFF),
        brightMagenta: Color(0xFFFF92DF),
        brightCyan: Color(0xFFA4FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFBD93F9),
        searchHitBackgroundCurrent: Color(0xFFFF5555),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'monokai':
      return const xt.TerminalTheme(
        background: Color(0xFF272822),
        foreground: Color(0xFFF8F8F2),
        cursor: Color(0xFFF8F8F2),
        selection: Color(0xFF49483E),
        black: Color(0xFF272822),
        red: Color(0xFFF92672),
        green: Color(0xFFA6E22E),
        yellow: Color(0xFFF4BF75),
        blue: Color(0xFF66D9EF),
        magenta: Color(0xFFAE81FF),
        cyan: Color(0xFFA1EFE4),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF75715E),
        brightRed: Color(0xFFF92672),
        brightGreen: Color(0xFFA6E22E),
        brightYellow: Color(0xFFF4BF75),
        brightBlue: Color(0xFF66D9EF),
        brightMagenta: Color(0xFFAE81FF),
        brightCyan: Color(0xFFA1EFE4),
        brightWhite: Color(0xFFF9F8F5),
        searchHitBackground: Color(0xFF66D9EF),
        searchHitBackgroundCurrent: Color(0xFFF92672),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'ubuntu':
      return const xt.TerminalTheme(
        background: Color(0xFF300A24),
        foreground: Color(0xFFEEEEEC),
        cursor: Color(0xFFEEEEEC),
        selection: Color(0xFF555753),
        black: Color(0xFF2E3436),
        red: Color(0xFFCC0000),
        green: Color(0xFF4E9A06),
        yellow: Color(0xFFC4A000),
        blue: Color(0xFF3465A4),
        magenta: Color(0xFF75507B),
        cyan: Color(0xFF06989A),
        white: Color(0xFFD3D7CF),
        brightBlack: Color(0xFF555753),
        brightRed: Color(0xFFEF2929),
        brightGreen: Color(0xFF8AE234),
        brightYellow: Color(0xFFFCE94F),
        brightBlue: Color(0xFF729FCF),
        brightMagenta: Color(0xFFAD7FA8),
        brightCyan: Color(0xFF34E2E2),
        brightWhite: Color(0xFFEEEEEC),
        searchHitBackground: Color(0xFF3465A4),
        searchHitBackgroundCurrent: Color(0xFFCC0000),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'tokyo_night':
      return const xt.TerminalTheme(
        background: Color(0xFF1A1B26),
        foreground: Color(0xFFC0CAF5),
        cursor: Color(0xFFC0CAF5),
        selection: Color(0xFF33467C),
        black: Color(0xFF15161E),
        red: Color(0xFFF7768E),
        green: Color(0xFF9ECE6A),
        yellow: Color(0xFFE0AF68),
        blue: Color(0xFF7AA2F7),
        magenta: Color(0xFFBB9AF7),
        cyan: Color(0xFF7DCFFF),
        white: Color(0xFFA9B1D6),
        brightBlack: Color(0xFF414868),
        brightRed: Color(0xFFF7768E),
        brightGreen: Color(0xFF9ECE6A),
        brightYellow: Color(0xFFE0AF68),
        brightBlue: Color(0xFF7AA2F7),
        brightMagenta: Color(0xFFBB9AF7),
        brightCyan: Color(0xFF7DCFFF),
        brightWhite: Color(0xFFC0CAF5),
        searchHitBackground: Color(0xFF7AA2F7),
        searchHitBackgroundCurrent: Color(0xFFF7768E),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'catppuccin_mocha':
      return const xt.TerminalTheme(
        background: Color(0xFF1E1E2E),
        foreground: Color(0xFFCDD6F4),
        cursor: Color(0xFFF5E0DC),
        selection: Color(0xFF45475A),
        black: Color(0xFF45475A),
        red: Color(0xFFF38BA8),
        green: Color(0xFFA6E3A1),
        yellow: Color(0xFFF9E2AF),
        blue: Color(0xFF89B4FA),
        magenta: Color(0xFFF5C2E7),
        cyan: Color(0xFF94E2D5),
        white: Color(0xFFBAC2DE),
        brightBlack: Color(0xFF585B70),
        brightRed: Color(0xFFF38BA8),
        brightGreen: Color(0xFFA6E3A1),
        brightYellow: Color(0xFFF9E2AF),
        brightBlue: Color(0xFF89B4FA),
        brightMagenta: Color(0xFFF5C2E7),
        brightCyan: Color(0xFF94E2D5),
        brightWhite: Color(0xFFA6ADC8),
        searchHitBackground: Color(0xFF89B4FA),
        searchHitBackgroundCurrent: Color(0xFFF38BA8),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'catppuccin_latte':
      return const xt.TerminalTheme(
        background: Color(0xFFEFF1F5),
        foreground: Color(0xFF4C4F69),
        cursor: Color(0xFFDC8A78),
        selection: Color(0xFFCCD0DA),
        black: Color(0xFF5C5F77),
        red: Color(0xFFD20F39),
        green: Color(0xFF40A02B),
        yellow: Color(0xFFDF8E1D),
        blue: Color(0xFF1E66F5),
        magenta: Color(0xFF8839EF),
        cyan: Color(0xFF179299),
        white: Color(0xFFACB0BE),
        brightBlack: Color(0xFFACB0BE),
        brightRed: Color(0xFFD20F39),
        brightGreen: Color(0xFF40A02B),
        brightYellow: Color(0xFFDF8E1D),
        brightBlue: Color(0xFF1E66F5),
        brightMagenta: Color(0xFF8839EF),
        brightCyan: Color(0xFF179299),
        brightWhite: Color(0xFFBCC0CC),
        searchHitBackground: Color(0xFF1E66F5),
        searchHitBackgroundCurrent: Color(0xFFD20F39),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'gruvbox':
      return const xt.TerminalTheme(
        background: Color(0xFF282828),
        foreground: Color(0xFFEBDBB2),
        cursor: Color(0xFFEBDBB2),
        selection: Color(0xFF504945),
        black: Color(0xFF282828),
        red: Color(0xFFCC241D),
        green: Color(0xFF98971A),
        yellow: Color(0xFFD79921),
        blue: Color(0xFF458588),
        magenta: Color(0xFFB16286),
        cyan: Color(0xFF689D6A),
        white: Color(0xFFA89984),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFFFB4934),
        brightGreen: Color(0xFFB8BB26),
        brightYellow: Color(0xFFFABD2F),
        brightBlue: Color(0xFF83A598),
        brightMagenta: Color(0xFFD3869B),
        brightCyan: Color(0xFF8EC07C),
        brightWhite: Color(0xFFEBDBB2),
        searchHitBackground: Color(0xFF458588),
        searchHitBackgroundCurrent: Color(0xFFCC241D),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'gruvbox_light':
      return const xt.TerminalTheme(
        background: Color(0xFFFBF1C7),
        foreground: Color(0xFF3C3836),
        cursor: Color(0xFF3C3836),
        selection: Color(0xFFEBDBB2),
        black: Color(0xFFFBF1C7),
        red: Color(0xFFCC241D),
        green: Color(0xFF98971A),
        yellow: Color(0xFFD79921),
        blue: Color(0xFF458588),
        magenta: Color(0xFFB16286),
        cyan: Color(0xFF689D6A),
        white: Color(0xFF7C6F64),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFF9D0006),
        brightGreen: Color(0xFF79740E),
        brightYellow: Color(0xFFB57614),
        brightBlue: Color(0xFF076678),
        brightMagenta: Color(0xFF8F3F71),
        brightCyan: Color(0xFF427B58),
        brightWhite: Color(0xFF3C3836),
        searchHitBackground: Color(0xFF458588),
        searchHitBackgroundCurrent: Color(0xFFCC241D),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'nord':
      return const xt.TerminalTheme(
        background: Color(0xFF2E3440),
        foreground: Color(0xFFD8DEE9),
        cursor: Color(0xFFD8DEE9),
        selection: Color(0xFF434C5E),
        black: Color(0xFF3B4252),
        red: Color(0xFFBF616A),
        green: Color(0xFFA3BE8C),
        yellow: Color(0xFFEBCB8B),
        blue: Color(0xFF81A1C1),
        magenta: Color(0xFFB48EAD),
        cyan: Color(0xFF88C0D0),
        white: Color(0xFFE5E9F0),
        brightBlack: Color(0xFF4C566A),
        brightRed: Color(0xFFBF616A),
        brightGreen: Color(0xFFA3BE8C),
        brightYellow: Color(0xFFEBCB8B),
        brightBlue: Color(0xFF81A1C1),
        brightMagenta: Color(0xFFB48EAD),
        brightCyan: Color(0xFF8FBCBB),
        brightWhite: Color(0xFFECEFF4),
        searchHitBackground: Color(0xFF81A1C1),
        searchHitBackgroundCurrent: Color(0xFFBF616A),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'one_dark':
      return const xt.TerminalTheme(
        background: Color(0xFF282C34),
        foreground: Color(0xFFABB2BF),
        cursor: Color(0xFF528BFF),
        selection: Color(0xFF3E4451),
        black: Color(0xFF282C34),
        red: Color(0xFFE06C75),
        green: Color(0xFF98C379),
        yellow: Color(0xFFD19A66),
        blue: Color(0xFF61AFEF),
        magenta: Color(0xFFC678DD),
        cyan: Color(0xFF56B6C2),
        white: Color(0xFFABB2BF),
        brightBlack: Color(0xFF5C6370),
        brightRed: Color(0xFFE06C75),
        brightGreen: Color(0xFF98C379),
        brightYellow: Color(0xFFD19A66),
        brightBlue: Color(0xFF61AFEF),
        brightMagenta: Color(0xFFC678DD),
        brightCyan: Color(0xFF56B6C2),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF61AFEF),
        searchHitBackgroundCurrent: Color(0xFFE06C75),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'solarized_dark':
      return const xt.TerminalTheme(
        background: Color(0xFF002B36),
        foreground: Color(0xFF839496),
        cursor: Color(0xFF839496),
        selection: Color(0xFF073642),
        black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFEEE8D5),
        brightBlack: Color(0xFF586E75),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFF268BD2),
        searchHitBackgroundCurrent: Color(0xFFDC322F),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'solarized_light':
      return const xt.TerminalTheme(
        background: Color(0xFFFDF6E3),
        foreground: Color(0xFF657B83),
        cursor: Color(0xFF657B83),
        selection: Color(0xFFEEE8D5),
        black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFEEE8D5),
        brightBlack: Color(0xFF586E75),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFF268BD2),
        searchHitBackgroundCurrent: Color(0xFFDC322F),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'rose_pine':
      return const xt.TerminalTheme(
        background: Color(0xFF191724),
        foreground: Color(0xFFE0DEF4),
        cursor: Color(0xFFE0DEF4),
        selection: Color(0xFF2A283E),
        black: Color(0xFF26233A),
        red: Color(0xFFEB6F92),
        green: Color(0xFF31748F),
        yellow: Color(0xFFF6C177),
        blue: Color(0xFF9CCFD8),
        magenta: Color(0xFFC4A7E7),
        cyan: Color(0xFFEBBCBA),
        white: Color(0xFFE0DEF4),
        brightBlack: Color(0xFF6E6A86),
        brightRed: Color(0xFFEB6F92),
        brightGreen: Color(0xFF31748F),
        brightYellow: Color(0xFFF6C177),
        brightBlue: Color(0xFF9CCFD8),
        brightMagenta: Color(0xFFC4A7E7),
        brightCyan: Color(0xFFEBBCBA),
        brightWhite: Color(0xFFE0DEF4),
        searchHitBackground: Color(0xFF9CCFD8),
        searchHitBackgroundCurrent: Color(0xFFEB6F92),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'rose_pine_moon':
      return const xt.TerminalTheme(
        background: Color(0xFF232136),
        foreground: Color(0xFFE0DEF4),
        cursor: Color(0xFFE0DEF4),
        selection: Color(0xFF44415A),
        black: Color(0xFF393552),
        red: Color(0xFFEB6F92),
        green: Color(0xFF3E8FB0),
        yellow: Color(0xFFF6C177),
        blue: Color(0xFF9CCFD8),
        magenta: Color(0xFFC4A7E7),
        cyan: Color(0xFFEA9A97),
        white: Color(0xFFE0DEF4),
        brightBlack: Color(0xFF6E6A86),
        brightRed: Color(0xFFEB6F92),
        brightGreen: Color(0xFF3E8FB0),
        brightYellow: Color(0xFFF6C177),
        brightBlue: Color(0xFF9CCFD8),
        brightMagenta: Color(0xFFC4A7E7),
        brightCyan: Color(0xFFEA9A97),
        brightWhite: Color(0xFFE0DEF4),
        searchHitBackground: Color(0xFF9CCFD8),
        searchHitBackgroundCurrent: Color(0xFFEB6F92),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'kanagawa':
      return const xt.TerminalTheme(
        background: Color(0xFF1F1F28),
        foreground: Color(0xFFC8C093),
        cursor: Color(0xFFC8C093),
        selection: Color(0xFF2D4F67),
        black: Color(0xFF16161D),
        red: Color(0xFFC34043),
        green: Color(0xFF76946A),
        yellow: Color(0xFFC0A36E),
        blue: Color(0xFF7E9CD8),
        magenta: Color(0xFF957FB8),
        cyan: Color(0xFF6A9589),
        white: Color(0xFFC8C093),
        brightBlack: Color(0xFF727169),
        brightRed: Color(0xFFE82424),
        brightGreen: Color(0xFF98BB6C),
        brightYellow: Color(0xFFE6C384),
        brightBlue: Color(0xFF7FB4CA),
        brightMagenta: Color(0xFF938AA9),
        brightCyan: Color(0xFF7AA89F),
        brightWhite: Color(0xFFDCD7BA),
        searchHitBackground: Color(0xFF7E9CD8),
        searchHitBackgroundCurrent: Color(0xFFC34043),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'everforest':
      return const xt.TerminalTheme(
        background: Color(0xFF2D353B),
        foreground: Color(0xFFD3C6AA),
        cursor: Color(0xFFD3C6AA),
        selection: Color(0xFF425047),
        black: Color(0xFF475258),
        red: Color(0xFFE67E80),
        green: Color(0xFFA7C080),
        yellow: Color(0xFFDBBC7F),
        blue: Color(0xFF7FBBB3),
        magenta: Color(0xFFD699B6),
        cyan: Color(0xFF83C092),
        white: Color(0xFFD3C6AA),
        brightBlack: Color(0xFF56635F),
        brightRed: Color(0xFFE67E80),
        brightGreen: Color(0xFFA7C080),
        brightYellow: Color(0xFFDBBC7F),
        brightBlue: Color(0xFF7FBBB3),
        brightMagenta: Color(0xFFD699B6),
        brightCyan: Color(0xFF83C092),
        brightWhite: Color(0xFFD3C6AA),
        searchHitBackground: Color(0xFF7FBBB3),
        searchHitBackgroundCurrent: Color(0xFFE67E80),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'palenight':
      return const xt.TerminalTheme(
        background: Color(0xFF292D3E),
        foreground: Color(0xFFA6ACCD),
        cursor: Color(0xFFA6ACCD),
        selection: Color(0xFF3E4451),
        black: Color(0xFF292D3E),
        red: Color(0xFFF07178),
        green: Color(0xFFC3E88D),
        yellow: Color(0xFFFFCB6B),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF89DDFF),
        white: Color(0xFFA6ACCD),
        brightBlack: Color(0xFF676E95),
        brightRed: Color(0xFFF07178),
        brightGreen: Color(0xFFC3E88D),
        brightYellow: Color(0xFFFFCB6B),
        brightBlue: Color(0xFF82AAFF),
        brightMagenta: Color(0xFFC792EA),
        brightCyan: Color(0xFF89DDFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF82AAFF),
        searchHitBackgroundCurrent: Color(0xFFF07178),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'cobalt2':
      return const xt.TerminalTheme(
        background: Color(0xFF132738),
        foreground: Color(0xFFFFFFFF),
        cursor: Color(0xFFFFFC00),
        selection: Color(0xFF1F4263),
        black: Color(0xFF000000),
        red: Color(0xFFFF0000),
        green: Color(0xFF33DE00),
        yellow: Color(0xFFFFE100),
        blue: Color(0xFF007AFF),
        magenta: Color(0xFFFF2C70),
        cyan: Color(0xFF00D8FF),
        white: Color(0xFFBBBBBB),
        brightBlack: Color(0xFF555555),
        brightRed: Color(0xFFFF5555),
        brightGreen: Color(0xFF55FF55),
        brightYellow: Color(0xFFFFFF55),
        brightBlue: Color(0xFF5555FF),
        brightMagenta: Color(0xFFFF55FF),
        brightCyan: Color(0xFF55FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF007AFF),
        searchHitBackgroundCurrent: Color(0xFFFF0000),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'ayu_dark':
      return const xt.TerminalTheme(
        background: Color(0xFF0A0E14),
        foreground: Color(0xFFBFBDB6),
        cursor: Color(0xFFFFCC66),
        selection: Color(0xFF253340),
        black: Color(0xFF000000),
        red: Color(0xFFFF3333),
        green: Color(0xFFB8CC52),
        yellow: Color(0xFFFFCC66),
        blue: Color(0xFF36A3D9),
        magenta: Color(0xFFF07178),
        cyan: Color(0xFF95E6CB),
        white: Color(0xFFBFBDB6),
        brightBlack: Color(0xFF686868),
        brightRed: Color(0xFFFF6565),
        brightGreen: Color(0xFFAAEE77),
        brightYellow: Color(0xFFFFD580),
        brightBlue: Color(0xFF68D4FF),
        brightMagenta: Color(0xFFFFA3A7),
        brightCyan: Color(0xFFB2F7E4),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF36A3D9),
        searchHitBackgroundCurrent: Color(0xFFFF3333),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'ayu_mirage':
      return const xt.TerminalTheme(
        background: Color(0xFF1F2430),
        foreground: Color(0xFFCCCFC6),
        cursor: Color(0xFFFFCC66),
        selection: Color(0xFF273747),
        black: Color(0xFF000000),
        red: Color(0xFFED8273),
        green: Color(0xFFA6CC70),
        yellow: Color(0xFFEAD575),
        blue: Color(0xFF6DAAFA),
        magenta: Color(0xFFF07178),
        cyan: Color(0xFF90E1C6),
        white: Color(0xFFCCCFC6),
        brightBlack: Color(0xFF686868),
        brightRed: Color(0xFFFF9366),
        brightGreen: Color(0xFFBAE67E),
        brightYellow: Color(0xFFFFD580),
        brightBlue: Color(0xFF73D0FF),
        brightMagenta: Color(0xFFFFA3A7),
        brightCyan: Color(0xFF95E6CB),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF6DAAFA),
        searchHitBackgroundCurrent: Color(0xFFED8273),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'synthwave84':
      return const xt.TerminalTheme(
        background: Color(0xFF2B213C),
        foreground: Color(0xFFFFFFFF),
        cursor: Color(0xFFFF7EDC),
        selection: Color(0xFF423D5B),
        black: Color(0xFF000000),
        red: Color(0xFFFF3333),
        green: Color(0xFF39FF14),
        yellow: Color(0xFFFEDD00),
        blue: Color(0xFF01CDFF),
        magenta: Color(0xFFFF71CE),
        cyan: Color(0xFF05FFA1),
        white: Color(0xFFD1D1E0),
        brightBlack: Color(0xFF686868),
        brightRed: Color(0xFFFF6666),
        brightGreen: Color(0xFF5DFF6B),
        brightYellow: Color(0xFFFEE838),
        brightBlue: Color(0xFF01CFFE),
        brightMagenta: Color(0xFFFF80F4),
        brightCyan: Color(0xFF05FFE1),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF01CDFF),
        searchHitBackgroundCurrent: Color(0xFFFF3333),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'github_dark':
      return const xt.TerminalTheme(
        background: Color(0xFF0D1117),
        foreground: Color(0xFFC9D1D9),
        cursor: Color(0xFFC9D1D9),
        selection: Color(0xFF161B22),
        black: Color(0xFF484F58),
        red: Color(0xFFFF7B72),
        green: Color(0xFF7EE787),
        yellow: Color(0xFFD2A8FF),
        blue: Color(0xFF79C0FF),
        magenta: Color(0xFFD2A8FF),
        cyan: Color(0xFF79C0FF),
        white: Color(0xFFC9D1D9),
        brightBlack: Color(0xFF6E7681),
        brightRed: Color(0xFFFFA198),
        brightGreen: Color(0xFF56D364),
        brightYellow: Color(0xFFE2CCFF),
        brightBlue: Color(0xFFA5D6FF),
        brightMagenta: Color(0xFFE2CCFF),
        brightCyan: Color(0xFFA5D6FF),
        brightWhite: Color(0xFFF0F6FC),
        searchHitBackground: Color(0xFF79C0FF),
        searchHitBackgroundCurrent: Color(0xFFFF7B72),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'github_light':
      return const xt.TerminalTheme(
        background: Color(0xFFFFFFFF),
        foreground: Color(0xFF24292F),
        cursor: Color(0xFF24292F),
        selection: Color(0xFFDDDFE1),
        black: Color(0xFF24292F),
        red: Color(0xFFCF222E),
        green: Color(0xFF116329),
        yellow: Color(0xFF4D2D00),
        blue: Color(0xFF0969DA),
        magenta: Color(0xFF8250DF),
        cyan: Color(0xFF1B7C83),
        white: Color(0xFF6E7781),
        brightBlack: Color(0xFF57606A),
        brightRed: Color(0xFFA40E26),
        brightGreen: Color(0xFF1A7F37),
        brightYellow: Color(0xFF633C01),
        brightBlue: Color(0xFF0550AE),
        brightMagenta: Color(0xFF8250DF),
        brightCyan: Color(0xFF3192AA),
        brightWhite: Color(0xFF8C959F),
        searchHitBackground: Color(0xFF0969DA),
        searchHitBackgroundCurrent: Color(0xFFCF222E),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'monokai_pro':
      return const xt.TerminalTheme(
        background: Color(0xFF2D2A2E),
        foreground: Color(0xFFFCFCFA),
        cursor: Color(0xFFFCFCFA),
        selection: Color(0xFF403E41),
        black: Color(0xFF2D2A2E),
        red: Color(0xFFFF6188),
        green: Color(0xFFA9DC76),
        yellow: Color(0xFFFFD866),
        blue: Color(0xFF78DCE8),
        magenta: Color(0xFFAB9DF2),
        cyan: Color(0xFF78DCE8),
        white: Color(0xFFFCFCFA),
        brightBlack: Color(0xFF727072),
        brightRed: Color(0xFFFF6188),
        brightGreen: Color(0xFFA9DC76),
        brightYellow: Color(0xFFFFD866),
        brightBlue: Color(0xFF78DCE8),
        brightMagenta: Color(0xFFAB9DF2),
        brightCyan: Color(0xFF78DCE8),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF78DCE8),
        searchHitBackgroundCurrent: Color(0xFFFF6188),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'atom_dark':
      return const xt.TerminalTheme(
        background: Color(0xFF1D1F21),
        foreground: Color(0xFFC5C8C6),
        cursor: Color(0xFFC5C8C6),
        selection: Color(0xFF373B41),
        black: Color(0xFF1D1F21),
        red: Color(0xFFCC6666),
        green: Color(0xFFB5BD68),
        yellow: Color(0xFFF0C674),
        blue: Color(0xFF81A2BE),
        magenta: Color(0xFFB294BB),
        cyan: Color(0xFF8ABEB7),
        white: Color(0xFFC5C8C6),
        brightBlack: Color(0xFF969896),
        brightRed: Color(0xFFCC6666),
        brightGreen: Color(0xFFB5BD68),
        brightYellow: Color(0xFFF0C674),
        brightBlue: Color(0xFF81A2BE),
        brightMagenta: Color(0xFFB294BB),
        brightCyan: Color(0xFF8ABEB7),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF81A2BE),
        searchHitBackgroundCurrent: Color(0xFFCC6666),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'material_ocean':
      return const xt.TerminalTheme(
        background: Color(0xFF1F2233),
        foreground: Color(0xFFC3CEE2),
        cursor: Color(0xFFFFCC00),
        selection: Color(0xFF2F3244),
        black: Color(0xFF1F2233),
        red: Color(0xFFF07178),
        green: Color(0xFFC3E88D),
        yellow: Color(0xFFFFCB6B),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF89DDFF),
        white: Color(0xFFC3CEE2),
        brightBlack: Color(0xFF676E95),
        brightRed: Color(0xFFF07178),
        brightGreen: Color(0xFFC3E88D),
        brightYellow: Color(0xFFFFCB6B),
        brightBlue: Color(0xFF82AAFF),
        brightMagenta: Color(0xFFC792EA),
        brightCyan: Color(0xFF89DDFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF82AAFF),
        searchHitBackgroundCurrent: Color(0xFFF07178),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'dracula_plus':
      return const xt.TerminalTheme(
        background: Color(0xFF222336),
        foreground: Color(0xFFF8F8F2),
        cursor: Color(0xFFF8F8F2),
        selection: Color(0xFF44475A),
        black: Color(0xFF21222C),
        red: Color(0xFFFF5555),
        green: Color(0xFF50FA7B),
        yellow: Color(0xFFF1FA8C),
        blue: Color(0xFFBD93F9),
        magenta: Color(0xFFFF79C6),
        cyan: Color(0xFF8BE9FD),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF6272A4),
        brightRed: Color(0xFFFF6E6E),
        brightGreen: Color(0xFF69FF94),
        brightYellow: Color(0xFFFFFFA5),
        brightBlue: Color(0xFFD6ACFF),
        brightMagenta: Color(0xFFFF92DF),
        brightCyan: Color(0xFFA4FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFBD93F9),
        searchHitBackgroundCurrent: Color(0xFFFF5555),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'night_owl':
      return const xt.TerminalTheme(
        background: Color(0xFF011627),
        foreground: Color(0xFFD6DEEB),
        cursor: Color(0xFFFFCC00),
        selection: Color(0xFF1D3B53),
        black: Color(0xFF011627),
        red: Color(0xFFEF5350),
        green: Color(0xFF22DA6E),
        yellow: Color(0xFFFFD740),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF7FDBCA),
        white: Color(0xFFD6DEEB),
        brightBlack: Color(0xFF637777),
        brightRed: Color(0xFFFF867A),
        brightGreen: Color(0xFF22DA6E),
        brightYellow: Color(0xFFFFE585),
        brightBlue: Color(0xFF82AAFF),
        brightMagenta: Color(0xFFC792EA),
        brightCyan: Color(0xFF7FDBCA),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF82AAFF),
        searchHitBackgroundCurrent: Color(0xFFEF5350),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'moonlight':
      return const xt.TerminalTheme(
        background: Color(0xFF1A1B26),
        foreground: Color(0xFFC0CAF5),
        cursor: Color(0xFFC0CAF5),
        selection: Color(0xFF33467C),
        black: Color(0xFF15161E),
        red: Color(0xFFF7768E),
        green: Color(0xFF9ECE6A),
        yellow: Color(0xFFE0AF68),
        blue: Color(0xFF7AA2F7),
        magenta: Color(0xFFBB9AF7),
        cyan: Color(0xFF7DCFFF),
        white: Color(0xFFA9B1D6),
        brightBlack: Color(0xFF414868),
        brightRed: Color(0xFFF7768E),
        brightGreen: Color(0xFF9ECE6A),
        brightYellow: Color(0xFFE0AF68),
        brightBlue: Color(0xFF7AA2F7),
        brightMagenta: Color(0xFFBB9AF7),
        brightCyan: Color(0xFF7DCFFF),
        brightWhite: Color(0xFFC0CAF5),
        searchHitBackground: Color(0xFF7AA2F7),
        searchHitBackgroundCurrent: Color(0xFFF7768E),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'cyberdyne':
      return const xt.TerminalTheme(
        background: Color(0xFF0C0015),
        foreground: Color(0xFFBFC2D5),
        cursor: Color(0xFF00CCFF),
        selection: Color(0xFF1A0030),
        black: Color(0xFF0C0015),
        red: Color(0xFFD4344C),
        green: Color(0xFF2FB76B),
        yellow: Color(0xFFE8A33C),
        blue: Color(0xFF5588CC),
        magenta: Color(0xFFBB44BB),
        cyan: Color(0xFF00CCCC),
        white: Color(0xFFBFC2D5),
        brightBlack: Color(0xFF555577),
        brightRed: Color(0xFFFF6677),
        brightGreen: Color(0xFF66FF88),
        brightYellow: Color(0xFFFFCC66),
        brightBlue: Color(0xFF88BBFF),
        brightMagenta: Color(0xFFFF77FF),
        brightCyan: Color(0xFF88EEEE),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF5588CC),
        searchHitBackgroundCurrent: Color(0xFFD4344C),
        searchHitForeground: Color(0xFFFFFFFF),
      );
    case 'nord_light':
      return const xt.TerminalTheme(
        background: Color(0xFFECEFF4),
        foreground: Color(0xFF2E3440),
        cursor: Color(0xFF2E3440),
        selection: Color(0xFFD8DEE9),
        black: Color(0xFF3B4252),
        red: Color(0xFFBF616A),
        green: Color(0xFFA3BE8C),
        yellow: Color(0xFFEBCB8B),
        blue: Color(0xFF81A1C1),
        magenta: Color(0xFFB48EAD),
        cyan: Color(0xFF88C0D0),
        white: Color(0xFFE5E9F0),
        brightBlack: Color(0xFF4C566A),
        brightRed: Color(0xFFBF616A),
        brightGreen: Color(0xFFA3BE8C),
        brightYellow: Color(0xFFEBCB8B),
        brightBlue: Color(0xFF81A1C1),
        brightMagenta: Color(0xFFB48EAD),
        brightCyan: Color(0xFF8FBCBB),
        brightWhite: Color(0xFFECEFF4),
        searchHitBackground: Color(0xFF81A1C1),
        searchHitBackgroundCurrent: Color(0xFFBF616A),
        searchHitForeground: Color(0xFF2E3440),
      );
    case 'dark':
    default:
      return const xt.TerminalTheme(
        background: Color(0xFF1E1E2E),
        foreground: Color(0xFFCDD6F4),
        cursor: Color(0xFFF5E0DC),
        selection: Color(0xFF45475A),
        black: Color(0xFF45475A),
        red: Color(0xFFF38BA8),
        green: Color(0xFFA6E3A1),
        yellow: Color(0xFFF9E2AF),
        blue: Color(0xFF89B4FA),
        magenta: Color(0xFFF5C2E7),
        cyan: Color(0xFF94E2D5),
        white: Color(0xFFBAC2DE),
        brightBlack: Color(0xFF585B70),
        brightRed: Color(0xFFF38BA8),
        brightGreen: Color(0xFFA6E3A1),
        brightYellow: Color(0xFFF9E2AF),
        brightBlue: Color(0xFF89B4FA),
        brightMagenta: Color(0xFFF5C2E7),
        brightCyan: Color(0xFF94E2D5),
        brightWhite: Color(0xFFA6ADC8),
        searchHitBackground: Color(0xFF89B4FA),
        searchHitBackgroundCurrent: Color(0xFFF38BA8),
        searchHitForeground: Color(0xFFFFFFFF),
      );
  }
}

List<String> get allTerminalThemeIds => const [
  'dark', 'dracula', 'monokai', 'ubuntu',
  'tokyo_night', 'catppuccin_mocha', 'catppuccin_latte',
  'gruvbox', 'gruvbox_light', 'nord', 'one_dark',
  'solarized_dark', 'solarized_light', 'rose_pine', 'rose_pine_moon',
  'kanagawa', 'everforest', 'palenight', 'cobalt2',
  'ayu_dark', 'ayu_mirage', 'synthwave84', 'github_dark', 'github_light',
  'monokai_pro', 'atom_dark', 'material_ocean', 'dracula_plus',
  'night_owl', 'moonlight', 'cyberdyne', 'nord_light',
];

String getTerminalThemeDisplayName(String id) {
  const names = {
    'dark': 'Catppuccin Dark',
    'dracula': 'Dracula',
    'monokai': 'Monokai',
    'ubuntu': 'Ubuntu',
    'tokyo_night': 'Tokyo Night',
    'catppuccin_mocha': 'Catppuccin Mocha',
    'catppuccin_latte': 'Catppuccin Latte',
    'gruvbox': 'Gruvbox Dark',
    'gruvbox_light': 'Gruvbox Light',
    'nord': 'Nord',
    'one_dark': 'One Dark',
    'solarized_dark': 'Solarized Dark',
    'solarized_light': 'Solarized Light',
    'rose_pine': 'Rose Pine',
    'rose_pine_moon': 'Rose Pine Moon',
    'kanagawa': 'Kanagawa',
    'everforest': 'Everforest Dark',
    'palenight': 'Material Palenight',
    'cobalt2': 'Cobalt2',
    'ayu_dark': 'Ayu Dark',
    'ayu_mirage': 'Ayu Mirage',
    'synthwave84': "Synthwave '84",
    'github_dark': 'GitHub Dark',
    'github_light': 'GitHub Light',
    'monokai_pro': 'Monokai Pro',
    'atom_dark': 'Atom One Dark',
    'material_ocean': 'Material Ocean',
    'dracula_plus': 'Dracula Plus',
    'night_owl': 'Night Owl',
    'moonlight': 'Moonlight',
    'cyberdyne': 'Cyberdyne',
    'nord_light': 'Nord Light',
  };
  return names[id] ?? id;
}
